spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
storage:
  s3:
    bucket: ${AWS_S3_BUCKET}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_S3_REGION}